const API_BASE_URL_DEVELOPMENT = 'http://localhost:5006';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const ENDPOINTS = {
    GET_ALL_ITEMS: 'api/Item',
    GET_ITEMS_BY_ID: 'api/Item',
    CREATE_ITEM: 'api/Item',
    UPDATE_ITEM: 'api/Item',
    DELETE_ITEM_BY_ID: 'api/Item'
};

const development = {
    API_URL_GET_ALL_ITEMS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_ITEMS}`,
    API_URL_GET_ITEM_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ITEMS_BY_ID}`,
    API_URL_CREATE_ITEM: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_ITEM}`,
    API_URL_UPDATE_ITEM: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_ITEM}`,
    API_URL_DELETE_ITEM_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_ITEM_BY_ID}`
};

const production = {
    API_URL_GET_ALL_ITEMS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_ITEMS}`,
    API_URL_GET_ITEM_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ITEMS_BY_ID}`,
    API_URL_CREATE_ITEM: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_ITEM}`,
    API_URL_UPDATE_ITEM: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_ITEM}`,
    API_URL_DELETE_ITEM_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_ITEM_BY_ID}`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;